version: "3.8"
services:
  Samals_FE: # 이름은 어떤걸로 지정해도 상관없음
    build:
      dockerfile: Dockerfile # dockerfile이름
      context: ./ # 도커파일 위치 명시
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/html:/usr/share/nginx/html

    ports:
      - "3001:3001" # port 맵핑
    stdin_open: true